### PR TITLE
Link integrity

### PR DESCRIPTION
**Pull request by gotcha**
Add event subscriber to setup link integrity.

Register adapters for tiles that have content which deserves link integrity.

Once and if merged to 5.x, we would work on forward port to master.

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

I have tested on Plone 5.2 Python 3.8. When I try to remove an item that is linked to an existing content tile, I get the link integrity warning. A link from an html tile has the same effect. Thanks!

**Comment by mauritsvanrees** [comment]
I have released `plone.app.blocks` 5.1.0 with this.

**Comment by mauritsvanrees** [comment]
I have updated this version in [5.2.9 pending](https://community.plone.org/t/plone-5-2-9-soft-released/15470).

**Comment by gotcha** [comment]
@petschki You are right that ``p.a.blocks`` cannot just depend on ``p.a.standardtiles``.

I will move the ``html`` and ``existingcontent`` adapters to ``p.a.standardtiles``.

**Pull request merged**
