### PR TITLE
Behavior shortname plone.layoutaware added

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by datakurre** [comment]
@jensens What are the requirements for plone.behavior >= 1.1? Does it work with Dexterity 1.x? Plone 4.x? If so, we could pin plone.behavior version for test buildout and document that requirement.

Not sure, why Plone 5 build is failing, because of this change.

**Comment by thet** [comment]
plone.behavior > 1.1 is necessary, but this is already a requirement in Plone 4.3.x.
Not sure about any version dependencies of plone.dexterity, but I use version 2.3.1 successfully in a 4.3 based project.

**Comment by jensens** [comment]
@asko, while untested I wont expect any issues for Plone >=4.0 <=4.2.x and it works afaict with 4.3.x

**Comment by datakurre** [comment]
Thanks. Pin >= 1.1 fixed build for Python 2.6. Single test still fails on Plone 5, which is strange.

**Comment by jensens** [comment]
the failure seems completly unrelated.

**Comment by datakurre** [comment]
Probably. I'm sure the test gets fixed once someone is working at the master for the next time and then this could be merged.

**Comment by jensens** [comment]
ok, test fixed and I'll merge now

**Pull request merged**
