### PR TITLE
Linkintegrity support for Plone 6.0

### PR DESCRIPTION
**Pull request by petschki**
Follow up from #99

### CODE REVIEW

**Review by Rudd-O — APPROVED** [review]

**Comment by Rudd-O** [comment]
Approved — but please ensure tests pass again.

**Comment by jensens** [comment]
I think we should drop Plone 5 support at this point.

**Comment by petschki** [comment]
ready to go ... can we stay in this major version or should it be bumped to 7 ?

**Comment by mauritsvanrees** [comment]
Since this drops 5.2 support, it is a breaking change. I have bumped the version to 7.0.0.
I have created branch 6.x from commit 0d4439a6f5a11451479f3e3f97c67d6e60df240a, which is the version bump after the previous release 6.0.1.  So:

- Branch 5.x is for Plone 5.2, Py 2/3.
- Branch 6.x is for Plone 5.2 and Plone 6, only Py 3. This is the only branch of these three that does not contain the link integrity support.
- master branch is for Plone 6 only.

I wonder if anyone will care for branch 6.x. It might happen. I have a few other packages that I try to keep running on both 5.2 and 6 on Python 3, like plone.namedfile and plone.scale. We'll see.

I do have a fix ready so `plone.app.blocks` works together with the Zope security fix, see issue #101. I will do that on the 6.x branch as well, and may use that for a possible Plone 6.0.0.2 release, so no great amount of extra code from this PR comes in.

**Pull request merged**
