### PR TITLE
Depend on plone.app.standardtiles

### PR DESCRIPTION
**Pull request by ale-rt**
Refs. #95
Refs. #94 that introduced an hard dependency on that package

### CODE REVIEW

**Comment by ale-rt** [comment]
Thanks @petschki, that's indeed a circular dependency.
It was a soft dependency in 5.0.1:
```
ale@avo:~/Code/plone/projects/coredev/5.2/src/plone.app.blocks$ git grep standardtiles 5.0.1
5.0.1:plone/app/blocks/subscribers.py:        if "plone.app.standardtiles.field" in tile_url:
5.0.1:plone/app/blocks/tests/test_contentlayout.py:  <div data-tile="./@@plone.app.standardtiles.html/example"
...
```
It became an hard one on in 5.1.0:
```
ale@avo:~/Code/plone/projects/coredev/5.2/src/plone.app.blocks$ git grep standardtiles 5.1.0
5.1.0:plone/app/blocks/linkintegrity.py:from plone.app.standardtiles import html
5.1.0:plone/app/blocks/linkintegrity.py:from plone.app.standardtiles import existingcontent
5.1.0:plone/app/blocks/subscribers.py:        if "plone.app.standardtiles.field" in tile_url:
5.1.0:plone/app/blocks/tests/test_contentlayout.py:  <div data-tile="./@@plone.app.standardtiles.html/example"
...
```

5.1.0 contains have #94 which is missing on master.

I think there is quite a lot to do here...

**Comment by petschki** [comment]
Regarding the hard dependency: I think `html` and `existingcontent` linkitegrity implementation should be done in `plone.app.standardtiles`

The soft dependency should really be solved differently maybe with an `el.attrib.get("data-tile-storage") == "skip"` which then could be set in `plone.app.standardtiles.field` ...

**Comment by ale-rt** [comment]
Yeah I am definitely convinced that `plone.app.blocks` should not depend on standard tiles

I updated #95 and I will close this PR.

> Regarding the hard dependency: I think `html` and `existingcontent` linkitegrity implementation should be done in `plone.app.standardtiles`
> 

Maybe the other way around (i.e., moving `plone.app.standardtiles.html` and `plone.app.standardtiles.existingcontent` to this package) will be better?
Anyway let's move the discussion in #95

**Comment by petschki** [comment]
Are there changes to merge into `5.x` or can we close it?

**Pull request closed without merging**
