### PR TITLE
Stay with bytes: serialize bytes not string

### PR DESCRIPTION
**Pull request by ksuess**
Fix for Mosaic issue https://github.com/plone/plone.app.mosaic/issues/480

### CODE REVIEW

**Comment by petschki** [comment]
I'm not really sure what's going on here. I was not able to reproduce your issue with mosaic as mentioned above. I think this lxml error has to do with some difference in OS compiled and custom compiled lxml libraries ... I'm actually using py3.7 (pyenv) with MacOS compiled lxml ... I can remember I had this error while switching to MacOS Big Sur without pyenv but since using pyenv this is gone ... but it might also be a solution to **not** use encoding here at all ...

/cc @jensens @datakurre  maybe have more ideas on this?

**Comment by ksuess** [comment]
This (my) PR is wrong and dangerous. The problem it tries to fix exists. But should be analyzed thoroughly:
**Why is bytes popping up, where is the true origin? There the problem should be fixed.**

**Comment by jensens** [comment]
@ksuess given your above comment you may want to create an issue referring this PR and close this one?

**Comment by ksuess** [comment]
Fixed by https://github.com/plone/plone.app.blocks/pull/85 with same changes but distinction by Python 2 / Python 3

**Pull request closed without merging**
