### PR TITLE
Enable output filters for content layout view

### PR DESCRIPTION
**Pull request by datakurre**
This would fix https://github.com/plone/plone.app.mosaic/issues/100 required for https://github.com/plone/plone.app.mosaic/issues/85

This would also restore support for Plone 4.2, which should make @hvelarde happy (should enable long pending c.cover upgrade to new p.app.blocks).

### CODE REVIEW

**Comment by vangheem** [comment]
Nice. Well, that was actually rather easy!

**Comment by datakurre** [comment]
I figured that we have no reason to support portal_transforms here, but can directly call outputfilters.

**Comment by datakurre** [comment]
@vangheem Should we care about safe html transform?

**Comment by vangheem** [comment]
Safe html should be used on text tiles only-- if that's possible.

**Comment by datakurre** [comment]
Text tiles are on layout, so either safe_html should be run to whole layout (with a lot of configuration to make it allow everything mosaic-), or text tiles should be parsed and transformed on save, probably with setter on behavior. Hopefully safe_html, can be called somewhat directly (portal_transform's caching etc feels unnecessary here).

**Comment by djay** [comment]
Isn't diazo an output filter?

**Comment by vangheem** [comment]
It's a transform.

**Comment by datakurre** [comment]
A lot of transforms in Plone. Diazo and Blocks are plone.transformchain (post publishing) transforms. Resolve UIDs and captions is a plone.outputfilters outputfilter, which again is a single transform in portal_transform – similarly to safe_html (and probably they are chained somehow in portal_transforms configuration so that text/x-plone-outputfilters-html becomes safe_html.

**Pull request merged**
