### PR TITLE
Provide new getLayoutsFromDirectory utility

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by datakurre** [comment]
But how OFS.Image.Files got transformed in the first place? The transform was already supposed to be opt-in by request (by a marker interface in the published object or request).

**Comment by vangheem** [comment]
I see what was going on. I've updated the PR to include only the one new utility the is needed now.

**Comment by datakurre** [comment]
@vangheem Ok, thanks. Travis show some Plone 4.x incompatibility. Possibly just small fix.

**Comment by vangheem** [comment]
pushed update, let's see how CI does now.

**Pull request merged**
