### PR TITLE
adapterize ILayoutAware

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by datakurre** [comment]
:+1: Very nice.

Should this be major version?

**Comment by jensens** [comment]
Yes indeed this should be major. I also like to discuss some details, maybe in a hangout? Digging through code often results in ideas with need to be balanced between backwards compatibility and beauty.

**Comment by gforcada** [comment]
@datakurre  @jensens I was reviewing the code and noticed that ``p.a.b.resource.PageSiteLayout`` and ``DefaultSiteLayout`` use the very exact same logic for ``_getLayout`` method, so I removed the one on ``PageSiteLayout``, should the class and ZCML be removed as well? Or at least put a deprecation notice there?

**Comment by jensens** [comment]
@gforcada I tried to keep some amount of bbb code, but we can talk about breaking things. The code  here is not widely spreaded nor core. Consuming code must be touched anyway.

**Comment by datakurre** [comment]
I'll merge these now, so we get started today with the latest architecture.

**Pull request merged**
