### PR TITLE
Moved tile integration for linkintegrity to plone.app.standardtiles

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This includes the fix from my PR #98 from earlier today. I needed them both.

You can test this together with https://github.com/plone/plone.app.standardtiles/pull/136

### CODE REVIEW

**Comment by wesleybl** [comment]
@mauritsvanrees  `collective.cover` implements link integrity with subscriber:

https://github.com/collective/collective.cover/blob/6b55d22460c79b55556ac0d4dabb52175daa32c4/src/collective/cover/subscribers.py#L36

Would `plone.app.standardtiles` (or plone.app.blocks) solve this problem without the need for a subscriber?

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees `collective.cover` implements link integrity with subscriber:
> 
> https://github.com/collective/collective.cover/blob/6b55d22460c79b55556ac0d4dabb52175daa32c4/src/collective/cover/subscribers.py#L36
> 
> Would `plone.app.standardtiles` (or plone.app.blocks) solve this problem without the need for a subscriber?

I think so. But you would need to write an adapter to `Retriever` for each tile.

When I look at [`get_referenced_objects`](https://github.com/collective/collective.cover/blob/e91b381b46d8418eca59d02e17962ad704c90092/src/collective/cover/content.py#L126-L151) which is called from the `collective.cover` subscriber, there is only a limited set of tiles for which any links/objects are retrieved. With the way from `plone.app.blocks`, all tiles are supported, as long as there is an adapter for each tile.

**Review by jensens — APPROVED** [review]

**Review by gotcha — APPROVED** [review]
LGTM

Thanks @mauritsvanrees

**Comment by mauritsvanrees** [comment]
I have made releases for Plone 5.2:

```
plone.app.blocks = 5.2.0
plone.app.standardtiles = 2.5.0
```

Porting this to Plone 6 is left as an exercise for the reader. ;-)

**Comment by petschki** [comment]
I didn't read it ...

**Pull request merged**
