### PR TITLE
WIP: index layout data and cleanup tile settings on edit

### PR DESCRIPTION
**Pull request by vangheem**
@datakurre this needs some review but I think this is what we want.

### CODE REVIEW

**Comment by datakurre** [comment]
Gets a bit complicated with shared layouts and rawhtml tiles, but I 
agree that it should be done.

I'll try to go through this tomorrow.

Nathan Van Gheem wrote:

**Comment by datakurre** [comment]
@vangheem I'm little worried about hardcoding SearchableText-indexing. It makes it impossible to add custom fields into SearchableText-index in TTW DX types.

Do you have something against collective.dexteritytextindexer? I would have been ok with supporting  indexing only with dexteritytextindexer and refactor this pull to define its IDexterityTextIndexFieldConverter adapters for indexed ILayoutAware-fields.

**Comment by vangheem** [comment]
I'm okay with something else. This PR, for now, is more of a discussion point and didn't think it was ready to merge.

The best deal is that dexteritytextindexer doesn't actually index all the tile content. I had no idea about IDexterityTextIndexFieldConverter so that sounds great.

**Comment by datakurre** [comment]
@vangheem So, we agree that it would be good enought to only support dextextindexer for searchable text indexing? That should clean up the pull, because we'd only need to care about ILayoutAware-fields. Simply restore "searchable" schema directive for content field and add the indexing logic into adapter.

**Comment by datakurre** [comment]
Also, feel free to add crazy style cheks into flake8-ignore list: https://github.com/plone/plone.app.blocks/blob/master/buildout.cfg#L14

**Comment by datakurre** [comment]
@neilferreira Ping. You were asking about tile indexing. Could you try if this works for you? (Just some Plone 4 incompatibility to fix and this could be merged for the next release.)

**Comment by neilferreira** [comment]
@vangheem @datakurre This is exactly what I was after!

I just spent 15mins adding some of the functionality that I imagined this would have as well.  See https://github.com/neilferreira/plone.app.blocks/commit/57b40acbb29a84f1ca051ea16a5767160abbd237

I have not tested any of this apart from just the fact that it now checks all the tile schema.

Few questions on your implementation:
1) What is the relevance of indexing the object (context) id as part of the layout's text in https://github.com/plone/plone.app.blocks/commit/9c696ec13328c12e642754c6b77906a565f7b289#diff-70236baa341441ea1fb615efb6472b4aR25 ?
2) I would have imagined that all RichText/Text fields would be getting indexed if they are a part of a tile.  Not just 'title' 'label' and 'content' - What are your thoughts on this?

What I've done in my implementation is also iterated through the Dict and List values,  we frequently make use of z3c.datagrid in our products.  You would ideally want the content from tabular data in a datagrid to be indexed as well, hence doing the recursive checking of all values.

**Comment by vangheem** [comment]
1) might be unnecessary. Just adding data to build the searchable text
2) title, label and content are not rich text. Getting rich text is done with the html parsing part of this code. 

I open for improvements!

**Comment by vangheem** [comment]
Please go ahead an work on/improve this PR with your ideas!

**Comment by datakurre** [comment]
I have no idea, how those tests did pass on Plone 5. Anyway, free to merge, unless @neilferreira has additions.

**Comment by gforcada** [comment]
@datakurre @vangheem please do not merge this code yet, @neilferreira still has to sign the CLA (or github organization has to be updated...) so until that is resolved no code should be merged (you don't want to make @polyester angry right? :D

**Comment by gforcada** [comment]
uh sorry, I totally missed that the pull request was from @vangheem ... it's getting late and I'm starting to fall asleep. Sorry for the noise, I thought I've seen a pull request from @neilferreira at some point in mosaic...

**Comment by datakurre** [comment]
@gforcada Thanks for reminding. I did accidentally merge minor pull from @neilferreira into Mosaic even it had tag about missing CLA. Reverted that.

I'll merge this pull now. We need new Blocks release for pending Mosaic pulls.

**Comment by datakurre** [comment]
I'll create an another pull later for refactoring this addition to support collective.dexteritytextindexer through (It's mostly about doing different ZCA-registration if dexteritytextindexer is available.

**Comment by gforcada** [comment]
@datakurre thanks for reverting the changes so promptly! @neilferreira would you like to sing the CLA so we can reapply and you can freely contribute to plone core? All info here: https://plone.org/foundation/contributors-agreement

**Comment by neilferreira** [comment]
@datakurre @gforcada I'm in the process of signing the CLA - I have signed the paperwork and passed it along to my employer to sign some documents of their own and pass along to you.  Give it a day or two.

**Comment by gforcada** [comment]
@neilferreira cool, great to hear that!

**Comment by neilferreira** [comment]
CLA has been signed.  I'm also part of the Plone foundation on Github.

**Pull request merged**
