### PR TITLE
Allow rendering of subtiles.

### PR DESCRIPTION
**Pull request by thet**
Now it's possible to reference and resolve tiles in tiles.

### CODE REVIEW

**Comment by datakurre** [comment]
@thet Do I read correctly that this does one extra data-tiles-resolving, so it’s one level down but not do it recursively.

Just checking. Nothing against this. This is also supported by Varnish ESI :)

**Comment by thet** [comment]
@datakurre no, it's recursively :) It calls itself as long as this condition evaluates to true ``if utils.headTileXPath(tree) or utils.bodyTileXPath(tree):`` https://github.com/plone/plone.app.blocks/pull/66/files#diff-65f1eb081e76d67bd2209f48a2bd831fR119

So, sub-sub tiles should also work.

I encountered a bug in a own project with a tile which whole template read like this:
```
<tal:code define="code view/code" condition="code" replace="structure code"/>
```

That ended up in a maximum recursion error, because the tile was never correctly rendered as it doesn't had a html/head/body structure.
Before my change this was silently ignored and the rendered HTML output included the ``<div data-tile="..`` reference.

So this is something to take into consideration - do tiles really need the html/head/body structure or should the also be allowed to only have html snippets? But that's a separate issue with a separate PR.

Sub tiles can help get more dynamic behavior into plone.app.blocks layouts. E.g. include tiles depending on some state, which isn't possible yet.

**Comment by datakurre** [comment]
Nice.

I’ll think later, how to make this into ESI support in plone.tiles (as we seem to be the only one ever using it ;). Conditional tiles make sense and would actually solve issues that I have had too.

Requirement of tiles being full HTML documents is an old one (from Deco era). It’s probably because there was (and might still be) support for reading head-tag contents from tiles into main document head. (That also complicated ESI support a bit, because that requires the resulting document to have explicit ESI tags for those head injections.)

Possibly we could assume tile without head or body tags being just the contents of body tag and being injected as they are.

**Comment by jensens** [comment]
@thet since this is a feature please increase the minor version number.

**Comment by thet** [comment]
@jensens  done.

**Pull request merged**
