### PR TITLE
provide abilty to set default grid system

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
@datakurre What do you think about this?

Additionally, perhaps we need a control panel for these?

**Comment by vangheem** [comment]
I wonder if we shouldn't use data-gridsystem attribute at all and just use the site setting? Otherwise, we won't be able to write generalized layouts that work with potentially any grid system. For instance, right now in plone.app.mosaic, we have identical layouts defined for plone 5 and 4 when it's not really necessary.

**Comment by datakurre** [comment]
I'd like it having a registry default, but also being overriddable with data-attribute. I think, it was kind of "ideal" in Deco design that everything could be in html. Registry would just give more convenience.

The attribute is not mandatory, so without the attribute, layouts would be generic?

Yet, probably this needs something more later to be compatible with the new theming policies. So that different sections could have different themes with different grid system. (My use case is to support e.g. small conference / event subsites with custom theme in a single Plone.)

Nathan Van Gheem kirjoitti to heinäkuuta 9 07:39:28 2015 GMT+0300:

**Comment by vangheem** [comment]
I agree, we need to keep the current behavior with the attribute.

So in plone.app.mosaic we should probably remove the use of that attribute with this change.

I think this PR is good to go though if you're okay merging.

**Comment by datakurre** [comment]
+1

p.a.mosaic may need some changes indeed. Probably removing data-attributes for this from example layouts. There is also a transform, which adds an additional body class if gridsystem is deco (to not apply deco classes for other gridsystems), which should now also check this setting. 

Nathan Van Gheem kirjoitti to heinäkuuta 9 09:26:44 2015 GMT+0300:

**Comment by vangheem** [comment]
Okay if I merge this?

**Comment by datakurre** [comment]
Please, do.

**Pull request merged**
