### PR TITLE
Add support for (static) content layouts

### PR DESCRIPTION
**Pull request by datakurre**
This is required for new WIP static content layout support in p.a.blocks and p.a.mosaic. In brief, enabling to be able to use static centrally managed layouts, but still be able override individual tile configurations using context specific persistent annotations.

Related to https://github.com/plone/plone.tiles/pull/4

### CODE REVIEW

**Comment by datakurre** [comment]
Should we now also move ++contentlayout++ -traverser and manifest-configuration from Mosaic into Blocks?

**Comment by vangheem** [comment]
Yes, I think it makes sense to move it there.

**Comment by vangheem** [comment]
@datakurre this PR is ready

**Comment by datakurre** [comment]
@vangheem 

Already 3.0 even we did not rename any properties on layout aware behavior? (I guess, bot renaming is still ok, because no migration required, but maybe we should save your proposed property names as comments so that anyone reading code would understand, what the properties mean :)

Then this https://github.com/plone/plone.tiles/pull/4#issuecomment-137183605

If postfixing urls with ?X-Tile-Persistent is OK, maybe we should add caching.

**Comment by vangheem** [comment]
layoutbehavior changes. We can do 2.3 if you prefer. I didn't end up renaming because migration was too scary :(. I can still do it if you prefer.

**Comment by datakurre** [comment]
Ok. Thanks. Let it be 3.0. Could you still add upgrade step for rolemap.xml? I can add content layout tests and do merge on Friday.

**Comment by vangheem** [comment]
Done.

**Pull request merged**
